"""
myproject Project (Generated by Panther on 2023-08-07)
"""

from pathlib import Path
from datetime import timedelta

from panther.utils import load_env
from panther.throttling import Throttling


BASE_DIR = Path(__name__).resolve().parent
env = load_env(BASE_DIR / '.env')

SECRET_KEY = env['SECRET_KEY']

# # # More Info: Https://PantherPy.GitHub.io/middlewares/
MIDDLEWARES = [
    ('panther.middlewares.db.Middleware', {'url': f'pantherdb://{BASE_DIR}/database.pdb'}),
]

# More Info: https://PantherPy.GitHub.io/configs/#user_model
USER_MODEL = 'panther.db.models.BaseUser'

# More Info: https://PantherPy.GitHub.io/authentications/
AUTHENTICATION = 'panther.authentications.JWTAuthentication'

# More Info: https://PantherPy.GitHub.io/monitoring/
MONITORING = True

# More Info: https://PantherPy.GitHub.io/log_queries/
LOG_QUERIES = True

# More Info: https://PantherPy.GitHub.io/throttling/
THROTTLING = Throttling(rate=60, duration=timedelta(minutes=1))

# More Info: https://PantherPy.GitHub.io/urls/
URLs = 'core/urls.py'
